/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.stonybrook.politech.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GeometricDetailsGenerated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -394360894638602923L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GeometricDetailsGenerated\",\"namespace\":\"com.stonybrook.politech.model\",\"fields\":[{\"name\":\"ID\",\"type\":\"string\"},{\"name\":\"geometryJSON\",\"type\":\"string\"},{\"name\":\"originalDistrictID\",\"type\":\"string\"},{\"name\":\"population\",\"type\":\"int\"},{\"name\":\"gop_vote\",\"type\":\"int\"},{\"name\":\"dem_vote\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GeometricDetailsGenerated> ENCODER =
      new BinaryMessageEncoder<GeometricDetailsGenerated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GeometricDetailsGenerated> DECODER =
      new BinaryMessageDecoder<GeometricDetailsGenerated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GeometricDetailsGenerated> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GeometricDetailsGenerated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GeometricDetailsGenerated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GeometricDetailsGenerated>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GeometricDetailsGenerated to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GeometricDetailsGenerated from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GeometricDetailsGenerated instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GeometricDetailsGenerated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence ID;
  @Deprecated public java.lang.CharSequence geometryJSON;
  @Deprecated public java.lang.CharSequence originalDistrictID;
  @Deprecated public int population;
  @Deprecated public int gop_vote;
  @Deprecated public int dem_vote;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GeometricDetailsGenerated() {}

  /**
   * All-args constructor.
   * @param ID The new value for ID
   * @param geometryJSON The new value for geometryJSON
   * @param originalDistrictID The new value for originalDistrictID
   * @param population The new value for population
   * @param gop_vote The new value for gop_vote
   * @param dem_vote The new value for dem_vote
   */
  public GeometricDetailsGenerated(java.lang.CharSequence ID, java.lang.CharSequence geometryJSON, java.lang.CharSequence originalDistrictID, java.lang.Integer population, java.lang.Integer gop_vote, java.lang.Integer dem_vote) {
    this.ID = ID;
    this.geometryJSON = geometryJSON;
    this.originalDistrictID = originalDistrictID;
    this.population = population;
    this.gop_vote = gop_vote;
    this.dem_vote = dem_vote;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ID;
    case 1: return geometryJSON;
    case 2: return originalDistrictID;
    case 3: return population;
    case 4: return gop_vote;
    case 5: return dem_vote;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ID = (java.lang.CharSequence)value$; break;
    case 1: geometryJSON = (java.lang.CharSequence)value$; break;
    case 2: originalDistrictID = (java.lang.CharSequence)value$; break;
    case 3: population = (java.lang.Integer)value$; break;
    case 4: gop_vote = (java.lang.Integer)value$; break;
    case 5: dem_vote = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ID' field.
   * @return The value of the 'ID' field.
   */
  public java.lang.CharSequence getID() {
    return ID;
  }


  /**
   * Sets the value of the 'ID' field.
   * @param value the value to set.
   */
  public void setID(java.lang.CharSequence value) {
    this.ID = value;
  }

  /**
   * Gets the value of the 'geometryJSON' field.
   * @return The value of the 'geometryJSON' field.
   */
  public java.lang.CharSequence getGeometryJSON() {
    return geometryJSON;
  }


  /**
   * Sets the value of the 'geometryJSON' field.
   * @param value the value to set.
   */
  public void setGeometryJSON(java.lang.CharSequence value) {
    this.geometryJSON = value;
  }

  /**
   * Gets the value of the 'originalDistrictID' field.
   * @return The value of the 'originalDistrictID' field.
   */
  public java.lang.CharSequence getOriginalDistrictID() {
    return originalDistrictID;
  }


  /**
   * Sets the value of the 'originalDistrictID' field.
   * @param value the value to set.
   */
  public void setOriginalDistrictID(java.lang.CharSequence value) {
    this.originalDistrictID = value;
  }

  /**
   * Gets the value of the 'population' field.
   * @return The value of the 'population' field.
   */
  public int getPopulation() {
    return population;
  }


  /**
   * Sets the value of the 'population' field.
   * @param value the value to set.
   */
  public void setPopulation(int value) {
    this.population = value;
  }

  /**
   * Gets the value of the 'gop_vote' field.
   * @return The value of the 'gop_vote' field.
   */
  public int getGopVote() {
    return gop_vote;
  }


  /**
   * Sets the value of the 'gop_vote' field.
   * @param value the value to set.
   */
  public void setGopVote(int value) {
    this.gop_vote = value;
  }

  /**
   * Gets the value of the 'dem_vote' field.
   * @return The value of the 'dem_vote' field.
   */
  public int getDemVote() {
    return dem_vote;
  }


  /**
   * Sets the value of the 'dem_vote' field.
   * @param value the value to set.
   */
  public void setDemVote(int value) {
    this.dem_vote = value;
  }

  /**
   * Creates a new GeometricDetailsGenerated RecordBuilder.
   * @return A new GeometricDetailsGenerated RecordBuilder
   */
  public static com.stonybrook.politech.model.GeometricDetailsGenerated.Builder newBuilder() {
    return new com.stonybrook.politech.model.GeometricDetailsGenerated.Builder();
  }

  /**
   * Creates a new GeometricDetailsGenerated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GeometricDetailsGenerated RecordBuilder
   */
  public static com.stonybrook.politech.model.GeometricDetailsGenerated.Builder newBuilder(com.stonybrook.politech.model.GeometricDetailsGenerated.Builder other) {
    if (other == null) {
      return new com.stonybrook.politech.model.GeometricDetailsGenerated.Builder();
    } else {
      return new com.stonybrook.politech.model.GeometricDetailsGenerated.Builder(other);
    }
  }

  /**
   * Creates a new GeometricDetailsGenerated RecordBuilder by copying an existing GeometricDetailsGenerated instance.
   * @param other The existing instance to copy.
   * @return A new GeometricDetailsGenerated RecordBuilder
   */
  public static com.stonybrook.politech.model.GeometricDetailsGenerated.Builder newBuilder(com.stonybrook.politech.model.GeometricDetailsGenerated other) {
    if (other == null) {
      return new com.stonybrook.politech.model.GeometricDetailsGenerated.Builder();
    } else {
      return new com.stonybrook.politech.model.GeometricDetailsGenerated.Builder(other);
    }
  }

  /**
   * RecordBuilder for GeometricDetailsGenerated instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GeometricDetailsGenerated>
    implements org.apache.avro.data.RecordBuilder<GeometricDetailsGenerated> {

    private java.lang.CharSequence ID;
    private java.lang.CharSequence geometryJSON;
    private java.lang.CharSequence originalDistrictID;
    private int population;
    private int gop_vote;
    private int dem_vote;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.stonybrook.politech.model.GeometricDetailsGenerated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.geometryJSON)) {
        this.geometryJSON = data().deepCopy(fields()[1].schema(), other.geometryJSON);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.originalDistrictID)) {
        this.originalDistrictID = data().deepCopy(fields()[2].schema(), other.originalDistrictID);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.population)) {
        this.population = data().deepCopy(fields()[3].schema(), other.population);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.gop_vote)) {
        this.gop_vote = data().deepCopy(fields()[4].schema(), other.gop_vote);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.dem_vote)) {
        this.dem_vote = data().deepCopy(fields()[5].schema(), other.dem_vote);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing GeometricDetailsGenerated instance
     * @param other The existing instance to copy.
     */
    private Builder(com.stonybrook.politech.model.GeometricDetailsGenerated other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.geometryJSON)) {
        this.geometryJSON = data().deepCopy(fields()[1].schema(), other.geometryJSON);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.originalDistrictID)) {
        this.originalDistrictID = data().deepCopy(fields()[2].schema(), other.originalDistrictID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.population)) {
        this.population = data().deepCopy(fields()[3].schema(), other.population);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.gop_vote)) {
        this.gop_vote = data().deepCopy(fields()[4].schema(), other.gop_vote);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.dem_vote)) {
        this.dem_vote = data().deepCopy(fields()[5].schema(), other.dem_vote);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'ID' field.
      * @return The value.
      */
    public java.lang.CharSequence getID() {
      return ID;
    }


    /**
      * Sets the value of the 'ID' field.
      * @param value The value of 'ID'.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder setID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ID' field has been set.
      * @return True if the 'ID' field has been set, false otherwise.
      */
    public boolean hasID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ID' field.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder clearID() {
      ID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'geometryJSON' field.
      * @return The value.
      */
    public java.lang.CharSequence getGeometryJSON() {
      return geometryJSON;
    }


    /**
      * Sets the value of the 'geometryJSON' field.
      * @param value The value of 'geometryJSON'.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder setGeometryJSON(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.geometryJSON = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'geometryJSON' field has been set.
      * @return True if the 'geometryJSON' field has been set, false otherwise.
      */
    public boolean hasGeometryJSON() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'geometryJSON' field.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder clearGeometryJSON() {
      geometryJSON = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'originalDistrictID' field.
      * @return The value.
      */
    public java.lang.CharSequence getOriginalDistrictID() {
      return originalDistrictID;
    }


    /**
      * Sets the value of the 'originalDistrictID' field.
      * @param value The value of 'originalDistrictID'.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder setOriginalDistrictID(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.originalDistrictID = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'originalDistrictID' field has been set.
      * @return True if the 'originalDistrictID' field has been set, false otherwise.
      */
    public boolean hasOriginalDistrictID() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'originalDistrictID' field.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder clearOriginalDistrictID() {
      originalDistrictID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'population' field.
      * @return The value.
      */
    public int getPopulation() {
      return population;
    }


    /**
      * Sets the value of the 'population' field.
      * @param value The value of 'population'.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder setPopulation(int value) {
      validate(fields()[3], value);
      this.population = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'population' field has been set.
      * @return True if the 'population' field has been set, false otherwise.
      */
    public boolean hasPopulation() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'population' field.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder clearPopulation() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'gop_vote' field.
      * @return The value.
      */
    public int getGopVote() {
      return gop_vote;
    }


    /**
      * Sets the value of the 'gop_vote' field.
      * @param value The value of 'gop_vote'.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder setGopVote(int value) {
      validate(fields()[4], value);
      this.gop_vote = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'gop_vote' field has been set.
      * @return True if the 'gop_vote' field has been set, false otherwise.
      */
    public boolean hasGopVote() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'gop_vote' field.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder clearGopVote() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'dem_vote' field.
      * @return The value.
      */
    public int getDemVote() {
      return dem_vote;
    }


    /**
      * Sets the value of the 'dem_vote' field.
      * @param value The value of 'dem_vote'.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder setDemVote(int value) {
      validate(fields()[5], value);
      this.dem_vote = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'dem_vote' field has been set.
      * @return True if the 'dem_vote' field has been set, false otherwise.
      */
    public boolean hasDemVote() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'dem_vote' field.
      * @return This builder.
      */
    public com.stonybrook.politech.model.GeometricDetailsGenerated.Builder clearDemVote() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GeometricDetailsGenerated build() {
      try {
        GeometricDetailsGenerated record = new GeometricDetailsGenerated();
        record.ID = fieldSetFlags()[0] ? this.ID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.geometryJSON = fieldSetFlags()[1] ? this.geometryJSON : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.originalDistrictID = fieldSetFlags()[2] ? this.originalDistrictID : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.population = fieldSetFlags()[3] ? this.population : (java.lang.Integer) defaultValue(fields()[3]);
        record.gop_vote = fieldSetFlags()[4] ? this.gop_vote : (java.lang.Integer) defaultValue(fields()[4]);
        record.dem_vote = fieldSetFlags()[5] ? this.dem_vote : (java.lang.Integer) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GeometricDetailsGenerated>
    WRITER$ = (org.apache.avro.io.DatumWriter<GeometricDetailsGenerated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GeometricDetailsGenerated>
    READER$ = (org.apache.avro.io.DatumReader<GeometricDetailsGenerated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ID);

    out.writeString(this.geometryJSON);

    out.writeString(this.originalDistrictID);

    out.writeInt(this.population);

    out.writeInt(this.gop_vote);

    out.writeInt(this.dem_vote);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ID = in.readString(this.ID instanceof Utf8 ? (Utf8)this.ID : null);

      this.geometryJSON = in.readString(this.geometryJSON instanceof Utf8 ? (Utf8)this.geometryJSON : null);

      this.originalDistrictID = in.readString(this.originalDistrictID instanceof Utf8 ? (Utf8)this.originalDistrictID : null);

      this.population = in.readInt();

      this.gop_vote = in.readInt();

      this.dem_vote = in.readInt();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ID = in.readString(this.ID instanceof Utf8 ? (Utf8)this.ID : null);
          break;

        case 1:
          this.geometryJSON = in.readString(this.geometryJSON instanceof Utf8 ? (Utf8)this.geometryJSON : null);
          break;

        case 2:
          this.originalDistrictID = in.readString(this.originalDistrictID instanceof Utf8 ? (Utf8)this.originalDistrictID : null);
          break;

        case 3:
          this.population = in.readInt();
          break;

        case 4:
          this.gop_vote = in.readInt();
          break;

        case 5:
          this.dem_vote = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










